add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$node\
$bun\
$golang\
$docker_context\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #e60000)"
error_symbol = "[❯](bold #4a4a4a)"

[directory]
truncation_length = 0
fish_style_pwd_dir_length = 0
style = "bold #1a1a1a"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold #ffbe00"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #e60000"
format = "([$all_status$ahead_behind]($style) )"

[nodejs]
symbol = " "
style = "bold #00a352"
format = "via [$symbol($version )]($style)"

[bun]
symbol = "󰛦 "
style = "bold #ea738d"
format = "via [$symbol($version )]($style)"

[golang]
symbol = " "
style = "bold #2ec4b6"
format = "via [$symbol($version )]($style)"

[docker_context]
symbol = " "
style = "bold #0055d4"
format = "on [$symbol$context]($style) "

[package]
disabled = true
